### PR TITLE
add ignore pattern option

### PR DESCRIPTION
**Pull request by MiniDigger**

### CODE REVIEW

**Comment by zml2008** [comment]
Could you elaborate on your usecase here?

I'm also surprised to see you choose regex here -- file patterns are usually done as globs. There should be a way to allow multiple patterns too if the forge people want to go ahead with this.

**Comment by zml2008** [comment]
(also you should know better than to PR from master...)

**Comment by MiniDigger** [comment]
oh sorry, was a long sunday, can fix the branch later. 
the usecase is that I am running diffpatch on a whole vanilla jar, which includes nbt files, which I need to ignore (additionally, I have a git repo in there too)
I am not sure how to implement glob patterns here (but can google I guess), but if that allows multiple patterns I am fine with that too.

for reference, this is my commit https://github.com/PaperMC/paperweight/commit/06a72cd90b8b0017641b06d7d354e5fbcc6b81a2

**Comment by LexManos** [comment]
Why do you have a git repo and nbt data in something you want to diff?
Why not just use a gradle copy task to filter out whatever you want?
Also why would you tell the patcher to apply a patch, by supplying it the diff, and then tell it not to apply the patch with a filter?
Overall this just doesn't make sense. Yes I get you already implemented it into your paperweight project, but it doesn't explain why you didn't use the other obvious/existing options.

As for the format, glob is preferred as it's simpler, And supporting multiple filters would be the way to go.

**Pull request closed without merging**
